### ISSUE TITLE
bn.js crash on unsubscribe

### ISSUE THREAD

**Issue by cmacma7** [cmacma7/bn#16]
disconnect jpthTdVQBTxGTvc4AAAV
delete SocketId2KeyMap m107:update
Disconnected:21
connect:22
disconnect mTo_fUITQGdQLhTfAAAW
***\* Error delete
delete SocketId2KeyMap 130:playTime,130:playState,130:programId,130:note,n1564:update,n1568:update,n1569:update,n3987:update,n3991:update,n4093:update,n4124:update,m107:update
Disconnected:22

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot set property 'socket' of undefined
    at callback_sub (/home/ubuntu/nodejs/bn/bn.js:1225:17)
    at RedisClient.<anonymous> (/home/ubuntu/nodejs/bn/bn.js:731:3)
    at RedisClient.EventEmitter.emit (events.js:98:17)
    at RedisClient.return_reply (/home/ubuntu/node_modules/redis/index.js:639:22)
    at HiredisReplyParser.<anonymous> (/home/ubuntu/node_modules/redis/index.js:282:14)
    at HiredisReplyParser.EventEmitter.emit (events.js:95:17)
    at HiredisReplyParser.execute (/home/ubuntu/node_modules/redis/lib/parser/hiredis.js:43:18)
    at RedisClient.on_data (/home/ubuntu/node_modules/redis/index.js:504:27)
    at Socket.<anonymous> (/home/ubuntu/node_modules/redis/index.js:82:14)
    at Socket.EventEmitter.emit (events.js:95:17)

**Comment by cmacma7** [comment]
We guess it is fixed

**Comment by cmacma7** [comment]
cannot reproduce right now because of previous fixes. Maybe fixed because of not using FIFO, instead, use closure variable.
